### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by gittykhirbat** [Jhsmit/ColiCoords#112]
Hi, I tried installing this library by:
1. First using the conda-forge command. It installed the required libraries in my virtual environment, running python3 (3.6.1). After installation, when I try to import it in the python command line, it throws an ImportError: No module named colicoords.

2. After this failed attempt, I thought I might try the longer option of installing using PyPi (+separate mahotas installation). Still getting the same ImportError.

Any ideas on what am I missing?

**Comment by Jhsmit** [comment]
Hi, thats strange, I'm not sure what could be causing this issue.

Which operating system are you on? Is your virtual environment a conda virtual environment? Do you then try to import by running python in this (activated) conda environment? Does this already give the error when running ``import colicoords``?

When I create a new conda environment on windows (either python 3.6.9 or 3.6.1) I can't reproduce the issue. 

If you installed mahotas 1.4.8 you might be running into [this](https://github.com/luispedro/mahotas/issues/108) issue, which should be fixed now in mahotas 1.4.9

**Comment by gittykhirbat** [comment]
Sorry, should have provided more details.

I am running this on MacOS 10.14.6 (Mojave)
I created a virtual environment using `virtualenv` for my project. I activated this virtual environment and installed colicoords using:
`conda install -c conda-forge colicoords`

I did a `conda list` next to check if it is installed in my current virtual environment. Positive so far.

I tried importing it within command line as well as a jupyter notebook instance by running `import colicoords`, it throws an error `ModuleNotFoundError: No module named 'colicoords'`


And I am running mahotas 1.4.9 version. Thanks for bringing that issue to notice, I re-installed mahotas in the same virtual environment.

**Comment by Jhsmit** [comment]
I don't have the ability to test on MacOS unfortunately. 

Why do you use ``virtualenv`` together with ``conda``? ``conda`` also gives you the ability to create python environments. Could you try making an virtual environment with ``conda create``, as described [here](https://uoa-eresearch.github.io/eresearch-cookbook/recipe/2014/11/20/conda/)?

Strange indeed that the package shows up in ``conda list`` but still gives this error.

Could your issue be related to [this issue](https://stackoverflow.com/questions/49522502/macos-python-modulenotfounderror-no-module-named-kiwisolver/49522647)?

**Comment by gittykhirbat** [comment]
I usually use `virtualenv` to create my environments. I made a `conda` environment and re-installed `colicoords` using the installation instructions.

This time there is a new error - `ImportError: cannot import name 'FitResults'`

I tried installing `symfit` from [here](https://anaconda.org/conda-forge/symfit) but the error persists.

Doing `conda list` shows me both `colicoords` and `symfit`.

Attaching the traceback here:

```
>>> import colicoords
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/gitanshkhirbat/opt/miniconda3/envs/env_try/lib/python3.6/site-packages/colicoords/__init__.py", line 2, in <module>
    from colicoords.cell import Cell, CellList
  File "/Users/gitanshkhirbat/opt/miniconda3/envs/env_try/lib/python3.6/site-packages/colicoords/cell.py", line 1, in <module>
    from colicoords.fitting import CellFit
  File "/Users/gitanshkhirbat/opt/miniconda3/envs/env_try/lib/python3.6/site-packages/colicoords/fitting.py", line 3, in <module>
    from colicoords.support import ArrayFitResults
  File "/Users/gitanshkhirbat/opt/miniconda3/envs/env_try/lib/python3.6/site-packages/colicoords/support.py", line 4, in <module>
    from symfit.core.fit import FitResults
ImportError: cannot import name 'FitResults'
```

I think it's not a `pip3` vs `pip` problem as I used `pip3` earlier.

**Comment by Jhsmit** [comment]
ah yes this is a known issue (#101), sorry about that. If you use symfit 0.4.8 it should work. 

I'll try to make a new ``ColiCoords`` release today to fix this problem

**Comment by gittykhirbat** [comment]
I tried installing `symfit 0.4.8` using `conda` in my environment, but it throws a `PackagesNotFoundError`. 

Would be great to use the new release of `ColiCoords`.

**Comment by Jhsmit** [comment]
ah yes I see now that symfit ``0.4.8`` isnt on conda-forge but only ``0.4.6`` is. 
I've released a new version of ``ColiCoords`` which should fix this ``ImportError``

Please let me know if you run into more issues.
